/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import DB.CRUD;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2ndyrGroupA
 */
public class ListOfUser extends javax.swing.JFrame implements ActionListener {

    DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    String email;

    /**
     * Creates new form ListOfUser
     */
    public ListOfUser() {
        initComponents();

        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listofuser = new javax.swing.JTable();
        logout = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        listofuser.setBackground(new java.awt.Color(255, 204, 204));
        listofuser.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        listofuser.setForeground(new java.awt.Color(255, 0, 51));
        listofuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Middle Name", "Last Name", "Username"
            }
        ));
        listofuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listofuserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listofuser);

        logout.setBackground(new java.awt.Color(255, 0, 102));
        logout.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(logout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listofuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listofuserMouseClicked
        JFrame parent = new JFrame();
        JPanel popup = new JPanel();
        JButton delete = new JButton();
        JButton edit = new JButton();
        int row = listofuser.getSelectedRow();
        email = model.getValueAt(row, 3).toString();
        delete.setText("Delete");
        edit.setText("EDIT");
        popup.add(edit);
        popup.add(delete);
        parent.add(popup);
        parent.pack();
        parent.setVisible(true);
        parent.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        delete.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                CRUD c = new CRUD();
                String query = "DELETE FROM `user` WHERE email='" + email + "'";
                model = (DefaultTableModel) listofuser.getModel();
                try {
                    Connection conn = c.dbConnect();
                    Statement st = conn.createStatement();
                    st.executeUpdate(query);

                } catch (Exception exe) {
                    System.out.println("got an exception");
                    System.out.println(exe.getMessage());
                }
                parent.setVisible(false);
                model.removeRow(row);

            }
        });
        edit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                CRUD c = new CRUD();
                String query = "SELECT * FROM user where email='" + email + "'";
                model = (DefaultTableModel) listofuser.getModel();
                parent.setVisible(false);
                try {
                    Connection conn = c.dbConnect();
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery(query);

                    while (rs.next()) {
                        String fname = rs.getString("first_name");
                        String mname = rs.getString("middle_name");
                        String lname = rs.getString("last_name");
                        String email = rs.getString("email");
                        String password = rs.getString("password");
                        
                        Update update = new Update();
                        update.setVisible(true);
                        parent.setVisible(false);
                        jPanel1.setVisible(false);
                        update.setFname(fname);
                        update.setMname(mname);
                        update.setLname(lname);
                        update.setEmail(email);
                        update.setPass(password);
                        update.setRepeatpass(password);
             
                        
                        

                    }

                } catch (Exception exe) {
                    System.out.println("got an exception on edit button");
                    System.out.println(exe.getMessage());
                }

            }
        });
    }//GEN-LAST:event_listofuserMouseClicked


    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    public  void showListOfUser() {
        CRUD c = new CRUD();
        String query = "SELECT first_name,middle_name,last_name,email FROM user";
        model = (DefaultTableModel) listofuser.getModel();
        try {
            Connection conn = c.dbConnect();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                String fname = rs.getString(1);
                String mname = rs.getString(2);
                String lname = rs.getString(3);
                String username = rs.getString(4);
                model.addRow(new Object[]{fname, mname, lname, username});

            }

        } catch (Exception e) {
            System.out.println("got an exception");
            System.out.println(e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listofuser;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JTextField Fname;

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
